version: 0.0
os: linux
files:
  - source: /geostore.war
    destination: /opt/tomcat/webapps
file_exists_behavior: OVERWRITE

permissions:
  - object: /opt/tomcat/webapps
    pattern: "*.war"
    owner: tomcat
    group: tomcat
    mode: 644
    type:
      - file

